#!/usr/bin/env node
/**
 * Regenerates src/data/shop.ts and public/shop/* from the Donaghys Direct
 * Shopify collection. Re-run whenever their prices, sizes or stock change:
 *
 *   node scripts/fetch-shop.mjs
 *
 * Source images are Shopify PNGs (~160KB each); they are re-encoded to WebP
 * here to keep the repo light. next/image handles delivery from there.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const COLLECTION = "https://donaghysdirect.co.uk/collections/the-stig-initiative";
const PRODUCT_BASE = "https://donaghysdirect.co.uk/products";
const IMAGE_DIR = join(process.cwd(), "public", "shop");
const DATA_FILE = join(process.cwd(), "src", "data", "shop.ts");
const WEBP_QUALITY = 82;

const COLOURS = ["Black", "Teal", "Navy", "Grey"];

/** Titles are inconsistently ordered ("Black Kids Hoodie" vs "Kids Black T-Shirt"),
 *  so match on keywords rather than word position. */
function parseTitle(title) {
  const audience = /kids/i.test(title) ? "kids" : "adult";
  const garment = /hoodie/i.test(title) ? "hoodie" : "tshirt";
  const colour = COLOURS.find((c) => new RegExp(c, "i").test(title));
  const logos = /\(2 logos\)/i.test(title) ? 2 : 1;
  const limitedEdition = /limited edition/i.test(title);
  if (!colour) throw new Error(`No colour found in title: ${title}`);
  return { audience, garment, colour, logos, limitedEdition };
}

const slugOf = (p) =>
  `${p.audience}-${p.garment}-${p.colour.toLowerCase()}-${p.logos}logo`;

const nameOf = (p) =>
  `${p.colour} ${p.audience === "kids" ? "Kids" : "Adult"} ${p.garment === "hoodie" ? "Hoodie" : "T-Shirt"}`;

/** Fetch a Shopify image and write it out as WebP. Returns bytes in/out. */
async function downloadAsWebp(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  const source = Buffer.from(await res.arrayBuffer());
  const webp = await sharp(source).webp({ quality: WEBP_QUALITY }).toBuffer();
  await writeFile(dest, webp);
  return { before: source.length, after: webp.length };
}

const res = await fetch(`${COLLECTION}/products.json?limit=250`);
if (!res.ok) throw new Error(`${res.status} fetching collection`);
const { products } = await res.json();
console.log(`Fetched ${products.length} products`);

// Start clean so renamed or delisted products don't leave orphans behind.
await rm(IMAGE_DIR, { recursive: true, force: true });
await mkdir(IMAGE_DIR, { recursive: true });
await mkdir(join(process.cwd(), "src", "data"), { recursive: true });

const items = [];
let bytesBefore = 0;
let bytesAfter = 0;

for (const p of products) {
  const meta = parseTitle(p.title);
  const slug = slugOf(meta);

  const prices = [...new Set(p.variants.map((v) => Number(v.price)))];
  if (prices.length > 1) {
    console.warn(`  ! ${slug}: variants differ in price (${prices.join(", ")}) — using lowest`);
  }

  const [front, back] = p.images;

  const f = await downloadAsWebp(front.src, join(IMAGE_DIR, `${slug}.webp`));
  bytesBefore += f.before;
  bytesAfter += f.after;

  if (back) {
    const b = await downloadAsWebp(back.src, join(IMAGE_DIR, `${slug}-back.webp`));
    bytesBefore += b.before;
    bytesAfter += b.after;
  }

  items.push({
    slug,
    name: nameOf(meta),
    ...meta,
    price: Math.min(...prices),
    sizes: p.variants.filter((v) => v.available).map((v) => v.title),
    url: `${PRODUCT_BASE}/${p.handle}`,
    image: `/shop/${slug}.webp`,
    imageBack: back ? `/shop/${slug}-back.webp` : null,
  });

  console.log(`  ${slug.padEnd(28)} £${Math.min(...prices).toFixed(2)}  ${back ? "2 images" : "1 image"}`);
}

// Adults first, then kids; hoodies before t-shirts; cheaper (1 logo) first.
const order = { adult: 0, kids: 1 };
items.sort(
  (a, b) =>
    order[a.audience] - order[b.audience] ||
    a.garment.localeCompare(b.garment) ||
    COLOURS.indexOf(a.colour) - COLOURS.indexOf(b.colour) ||
    a.logos - b.logos,
);

const file = `// Generated by scripts/fetch-shop.mjs — do not edit by hand.
// Source: ${COLLECTION}
// Prices and stock are set by Donaghys Direct; re-run the script to refresh.

export type ShopItem = {
  slug: string;
  name: string;
  audience: "adult" | "kids";
  garment: "hoodie" | "tshirt";
  colour: string;
  logos: 1 | 2;
  limitedEdition: boolean;
  price: number;
  sizes: string[];
  url: string;
  image: string;
  imageBack: string | null;
};

export const COLLECTION_URL = "${COLLECTION}";

export const SHOP_ITEMS: ShopItem[] = ${JSON.stringify(items, null, 2)};
`;

await writeFile(DATA_FILE, file);

const mb = (n) => (n / 1024 / 1024).toFixed(2);
console.log(`\nWrote ${DATA_FILE} (${items.length} items)`);
console.log(`Images: ${mb(bytesBefore)} MB PNG -> ${mb(bytesAfter)} MB WebP`);
