// Generated by scripts/fetch-shop.mjs — do not edit by hand.
// Source: https://donaghysdirect.co.uk/collections/the-stig-initiative
// Prices and stock are set by Donaghys Direct; re-run the script to refresh.

export type ShopItem = {
  slug: string;
  name: string;
  audience: "adult" | "kids";
  garment: "hoodie" | "tshirt";
  colour: string;
  logos: 1 | 2;
  limitedEdition: boolean;
  price: number;
  sizes: string[];
  url: string;
  image: string;
  imageBack: string | null;
};

export const COLLECTION_URL = "https://donaghysdirect.co.uk/collections/the-stig-initiative";

export const SHOP_ITEMS: ShopItem[] = [
  {
    "slug": "adult-hoodie-black-1logo",
    "name": "Black Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Black",
    "logos": 1,
    "limitedEdition": true,
    "price": 36,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-adult-hoodie-1-logo",
    "image": "/shop/adult-hoodie-black-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-hoodie-black-2logo",
    "name": "Black Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Black",
    "logos": 2,
    "limitedEdition": true,
    "price": 39.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-adult-hoodie-2-logos",
    "image": "/shop/adult-hoodie-black-2logo.webp",
    "imageBack": "/shop/adult-hoodie-black-2logo-back.webp"
  },
  {
    "slug": "adult-hoodie-navy-1logo",
    "name": "Navy Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Navy",
    "logos": 1,
    "limitedEdition": false,
    "price": 36,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-navy-hoodie-1-logo",
    "image": "/shop/adult-hoodie-navy-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-hoodie-navy-2logo",
    "name": "Navy Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Navy",
    "logos": 2,
    "limitedEdition": false,
    "price": 39.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-navy-hoodie-2-logos",
    "image": "/shop/adult-hoodie-navy-2logo.webp",
    "imageBack": "/shop/adult-hoodie-navy-2logo-back.webp"
  },
  {
    "slug": "adult-hoodie-grey-1logo",
    "name": "Grey Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Grey",
    "logos": 1,
    "limitedEdition": false,
    "price": 36,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-grey-hoodie-1-logo",
    "image": "/shop/adult-hoodie-grey-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-hoodie-grey-2logo",
    "name": "Grey Adult Hoodie",
    "audience": "adult",
    "garment": "hoodie",
    "colour": "Grey",
    "logos": 2,
    "limitedEdition": false,
    "price": 39.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-grey-hoodie-2-logos",
    "image": "/shop/adult-hoodie-grey-2logo.webp",
    "imageBack": "/shop/adult-hoodie-grey-2logo-back.webp"
  },
  {
    "slug": "adult-tshirt-black-1logo",
    "name": "Black Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Black",
    "logos": 1,
    "limitedEdition": true,
    "price": 18.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-adult-t-shirt-1-logo",
    "image": "/shop/adult-tshirt-black-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-tshirt-black-2logo",
    "name": "Black Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Black",
    "logos": 2,
    "limitedEdition": true,
    "price": 22,
    "sizes": [
      "XS",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-adult-t-shirt-2-logos",
    "image": "/shop/adult-tshirt-black-2logo.webp",
    "imageBack": "/shop/adult-tshirt-black-2logo-back.webp"
  },
  {
    "slug": "adult-tshirt-teal-1logo",
    "name": "Teal Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Teal",
    "logos": 1,
    "limitedEdition": false,
    "price": 18.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-teal-t-shirt-1-logo",
    "image": "/shop/adult-tshirt-teal-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-tshirt-teal-2logo",
    "name": "Teal Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Teal",
    "logos": 2,
    "limitedEdition": false,
    "price": 22,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-teal-t-shirt-2-logos",
    "image": "/shop/adult-tshirt-teal-2logo.webp",
    "imageBack": "/shop/adult-tshirt-teal-2logo-back.webp"
  },
  {
    "slug": "adult-tshirt-navy-1logo",
    "name": "Navy Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Navy",
    "logos": 1,
    "limitedEdition": false,
    "price": 18.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-navy-t-shirt-1-logo",
    "image": "/shop/adult-tshirt-navy-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-tshirt-navy-2logo",
    "name": "Navy Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Navy",
    "logos": 2,
    "limitedEdition": false,
    "price": 22,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-navy-t-shirt-2-logos",
    "image": "/shop/adult-tshirt-navy-2logo.webp",
    "imageBack": "/shop/adult-tshirt-navy-2logo-back.webp"
  },
  {
    "slug": "adult-tshirt-grey-1logo",
    "name": "Grey Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Grey",
    "logos": 1,
    "limitedEdition": false,
    "price": 18.5,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-adult-grey-t-shirt-1-logo",
    "image": "/shop/adult-tshirt-grey-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "adult-tshirt-grey-2logo",
    "name": "Grey Adult T-Shirt",
    "audience": "adult",
    "garment": "tshirt",
    "colour": "Grey",
    "logos": 2,
    "limitedEdition": false,
    "price": 22,
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "url": "https://donaghysdirect.co.uk/products/adult-grey-t-shirt",
    "image": "/shop/adult-tshirt-grey-2logo.webp",
    "imageBack": "/shop/adult-tshirt-grey-2logo-back.webp"
  },
  {
    "slug": "kids-hoodie-black-1logo",
    "name": "Black Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Black",
    "logos": 1,
    "limitedEdition": true,
    "price": 26.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-kids-hoodie-1-logo",
    "image": "/shop/kids-hoodie-black-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-hoodie-black-2logo",
    "name": "Black Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Black",
    "logos": 2,
    "limitedEdition": true,
    "price": 30,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-black-kids-hoodie-2-logos",
    "image": "/shop/kids-hoodie-black-2logo.webp",
    "imageBack": "/shop/kids-hoodie-black-2logo-back.webp"
  },
  {
    "slug": "kids-hoodie-teal-1logo",
    "name": "Teal Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Teal",
    "logos": 1,
    "limitedEdition": false,
    "price": 26.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-teal-hoodie-1-logo",
    "image": "/shop/kids-hoodie-teal-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-hoodie-teal-2logo",
    "name": "Teal Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Teal",
    "logos": 2,
    "limitedEdition": false,
    "price": 30,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-teal-hoodie-2-logos",
    "image": "/shop/kids-hoodie-teal-2logo.webp",
    "imageBack": "/shop/kids-hoodie-teal-2logo-back.webp"
  },
  {
    "slug": "kids-hoodie-navy-1logo",
    "name": "Navy Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Navy",
    "logos": 1,
    "limitedEdition": false,
    "price": 26.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-navy-hoodie-1-logo",
    "image": "/shop/kids-hoodie-navy-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-hoodie-navy-2logo",
    "name": "Navy Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Navy",
    "logos": 2,
    "limitedEdition": false,
    "price": 30,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-navy-hoodie-2-logos",
    "image": "/shop/kids-hoodie-navy-2logo.webp",
    "imageBack": "/shop/kids-hoodie-navy-2logo-back.webp"
  },
  {
    "slug": "kids-hoodie-grey-1logo",
    "name": "Grey Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Grey",
    "logos": 1,
    "limitedEdition": false,
    "price": 26.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-grey-hoodie-1-logo",
    "image": "/shop/kids-hoodie-grey-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-hoodie-grey-2logo",
    "name": "Grey Kids Hoodie",
    "audience": "kids",
    "garment": "hoodie",
    "colour": "Grey",
    "logos": 2,
    "limitedEdition": false,
    "price": 30,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-grey-hoodie-2-logos",
    "image": "/shop/kids-hoodie-grey-2logo.webp",
    "imageBack": "/shop/kids-hoodie-grey-2logo-back.webp"
  },
  {
    "slug": "kids-tshirt-black-1logo",
    "name": "Black Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Black",
    "logos": 1,
    "limitedEdition": true,
    "price": 10.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-kids-black-t-shirt-1-logo",
    "image": "/shop/kids-tshirt-black-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-tshirt-black-2logo",
    "name": "Black Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Black",
    "logos": 2,
    "limitedEdition": true,
    "price": 14,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-limited-edition-kids-black-t-shirt-2-logos",
    "image": "/shop/kids-tshirt-black-2logo.webp",
    "imageBack": "/shop/kids-tshirt-black-2logo-back.webp"
  },
  {
    "slug": "kids-tshirt-teal-1logo",
    "name": "Teal Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Teal",
    "logos": 1,
    "limitedEdition": false,
    "price": 10.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-teal-t-shirt-1-logo",
    "image": "/shop/kids-tshirt-teal-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-tshirt-teal-2logo",
    "name": "Teal Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Teal",
    "logos": 2,
    "limitedEdition": false,
    "price": 14,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-teal-t-shirt-2-logos",
    "image": "/shop/kids-tshirt-teal-2logo.webp",
    "imageBack": "/shop/kids-tshirt-teal-2logo-back.webp"
  },
  {
    "slug": "kids-tshirt-navy-1logo",
    "name": "Navy Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Navy",
    "logos": 1,
    "limitedEdition": false,
    "price": 10.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-navy-t-shirt-1-logo",
    "image": "/shop/kids-tshirt-navy-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-tshirt-navy-2logo",
    "name": "Navy Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Navy",
    "logos": 2,
    "limitedEdition": false,
    "price": 14,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-navy-t-shirt-2-logos",
    "image": "/shop/kids-tshirt-navy-2logo.webp",
    "imageBack": "/shop/kids-tshirt-navy-2logo-back.webp"
  },
  {
    "slug": "kids-tshirt-grey-1logo",
    "name": "Grey Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Grey",
    "logos": 1,
    "limitedEdition": false,
    "price": 10.5,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-grey-t-shirt-1-logo",
    "image": "/shop/kids-tshirt-grey-1logo.webp",
    "imageBack": null
  },
  {
    "slug": "kids-tshirt-grey-2logo",
    "name": "Grey Kids T-Shirt",
    "audience": "kids",
    "garment": "tshirt",
    "colour": "Grey",
    "logos": 2,
    "limitedEdition": false,
    "price": 14,
    "sizes": [
      "5-6",
      "7-8",
      "9-11",
      "12-13"
    ],
    "url": "https://donaghysdirect.co.uk/products/the-stig-initiative-kids-grey-t-shirt-2-logos",
    "image": "/shop/kids-tshirt-grey-2logo.webp",
    "imageBack": "/shop/kids-tshirt-grey-2logo-back.webp"
  }
];
